version: '3.3'
services:
    focal:
        image: charlesportwoodii/ubuntu:20.04-build
        command: bash -lc "make build fpm_debian VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    jammy:
        image: charlesportwoodii/ubuntu:22.04-build
        command: bash -lc "make build fpm_debian VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    noble:
        image: charlesportwoodii/ubuntu:24.04-build
        command: bash -lc "make build fpm_debian VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    centos7:
        image: charlesportwoodii/centos:7-build
        command: bash -lc "make build fpm_rpm VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    rhel7:
        image: charlesportwoodii/rhel:7-build
        command: bash -lc "make build fpm_rpm VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    alpine3.11:
        image: charlesportwoodii/alpine:3.11-build
        command: bash -lc "make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER
    alpine3.14:
        image: charlesportwoodii/alpine:3.14-build
        command: bash -lc "make build fpm_alpine VERSION=$VERSION RELEASEVER=$RELEASEVER"
        volumes:
            - ${PWD-.}:/data
        working_dir: /data
        environment:
            - VERSION=$VERSION
            - RELEASEVER=$RELEASEVER


